### ISSUE TITLE
homebridge PHP

### ISSUE THREAD

**Issue by VanGog86** [echoromeo/pynobo#10]
Good day!
I have no experience with python. But I was very interested in your project. Tell me how can I call your script from php?

**Comment by echoromeo** [comment]
Hi!
Unfortunately I have no idea how to call python scripts from PHP, you will have to goolge it like everyone else.
Good luck!

**Comment by VanGog86** [comment]
Thanks for the answer! Can you tell me what you need to do for the initial launch of the script? Thank you in advance )

**Comment by echoromeo** [comment]
I admit the documentation leaves something to be desired...

To get started, call using the three last digits in the hub serial

    glen = nobo('123') 

or full serial and IP if you do not want to discover on UDP:

    glen = nobo('123123123123', '10.0.0.128', False)

after that you can start playing around with the different dictionaries that should be loaded with whatever the hub gave you:

    glen.hub_info
    glen.zones
    glen.components
    glen.week_profiles
    glen.overrides
    glen.temperatures

Have fun!
