### ISSUE TITLE
Implementation guide

### ISSUE THREAD

**Issue by tachalainen** [echoromeo/pynobo#15]
Hey,

First of all, thanks for doing this.
Been searching a while to integreate my hub to Home Assistant.

But, a newbie question..
How do I get this in to my system?

Best regards,

**Comment by echoromeo** [comment]
Hi, you might want to have a look at https://github.com/echoromeo/hanobo. The readme there will help you get stuff into HA.
However, I have had a bit of a lack of motivation improving and bugfixing, so as you can see from the issues there it might not work 100% on the latest version of HA. 
If you wish to contribute I would greatly appreciate it!

**Comment by echoromeo** [comment]
No response = positive response? Closing
