### ISSUE TITLE
has_temp_sensor and current temperature of component

### ISSUE THREAD

**Issue by fetchinson** [echoromeo/pynobo#33]
This won't be a real issue, more like a question:

In short: basically I can't get the current temperatures of any of the units, although I'd think this should be possible.

Longer story:

I have a Nobo Eco Hub and a number of NCU-2R units, everything is working very well, pynobo also sees the entire system, there are no problems at all, thanks a lot for the code!

What I'm wondering is this: how is it that the desired temperature of NCU-2R units can be set (in many different ways, app, on the unit itself using the physical buttons, etc), yet the current temperature cannot be read out. The reason I think it can't be read out is that in the code you have, line 269,

`        "168": Model("168", Model.THERMOSTAT_HEATER, "NCU-2R", supports_comfort=True, supports_eco=True),`

So has_temp_sensor is False by default. And indeed the hub.temperatures ordered dict is always blank. The G00 response doesn't contain Y02 apparently (I use the example code from the README). Looking at MODELS it looks like only 

`        "234": Model("234", Model.CONTROL_PANEL, "SW4", has_temp_sensor=True),`

has_temp_sensor=True so I'd think pynobo will only report temperatures from this thing.

But I guess all units, even the simplest ones (with a thermostat) must know the temperature somehow, otherwise how do they know when to switch on or off, so why can't we read out this information? What is also suspicious is that on the official app the current temperature is not displayed anywhere either.

It's of course possible that I'm misunderstanding something.

**Comment by oyvindwe** [comment]
The hub only reports temperature for SW4 devices. I assume the other devices don't even transmit the temperature to the hub, and only use it internally.

The list of the various models and characteristics is based on heuristics. I don't have any SW4 myself, and I don't get any Y02 messages (see [API description](https://www.glendimplex.no/media/15650/nobo-hub-api-v-1-1-integration-for-advanced-users.pdf)) at all.

**Comment by fetchinson** [comment]
Thanks a lot, it's clear now.

In any case it's a bit surprising, one would think this wouldn't be a big addition from Nobo.
