### ISSUE TITLE
"No route to host" when hub is lost

### ISSUE THREAD

**Issue by echoromeo** [echoromeo/pynobo#9]
I get this error message when testing overnight in Home Assistant.
I guess this happens when the hub restarts:
Catch this exception as well?

```
Log Details (ERROR)
Sun Jun 17 2018 23:19:57 GMT+0200 (Central European Summer Time)

Unhandeled exception: [Errno 113] No route to host
Traceback (most recent call last):
  File "/config/custom_components/climate/nobo_hub.py", line 536, in socket_receive
    resp = self.get_response(True)
  File "/config/custom_components/climate/nobo_hub.py", line 507, in get_response
    response += self.client.recv(bufsize)
OSError: [Errno 113] No route to host
```

**Comment by capelevy** [comment]
We need to catch some sort of OSError, maybe handle the network exception here:
https://github.com/echoromeo/pynobo/blob/e6e578647971ccaa263bdeef9fa29b09603e021a/nobo.py#L397
I guess this is a retry'able error :)

**Comment by sturlahallas** [comment]
Hi. Is it possible to see how you've implemented this in Home Assistant?

**Comment by echoromeo** [comment]
Hi @sturlahallas, 
At the moment the Home Assistant implementation is a poorly implemented hack, but since I am a bit stuck at the moment I will make repo with what I have, I hope I will have time for it this weekend.

**Comment by gulgummiand** [comment]
@sturlahallas , my plan was to  implement an MQTT client in the python script and let this run standalone, and rather just inteface my MQTT broker from OpenHAB.

**Comment by echoromeo** [comment]
@sturlahallas, as promised: [https://github.com/echoromeo/hanobo](url)

**Comment by capelevy** [comment]
@echoromeo, I have rewritten the reconnect logic a bit, and started catching the OSError you were seeing. I cannot reproduce the "No route to host" by playing with network connections, could you check the dev_better_reconnect_stability branch, and see if that solves the problem?

**Comment by echoromeo** [comment]
@capelevy nice! will do

**Comment by echoromeo** [comment]
Unfortunately I still get the same "No route to host". It looks like I will have to set up the dev environment and get some more detailed debug output.

**Comment by bubbzy** [comment]
Hi! Been playing around with your Home Assistant implementation and found a couple of issues. Would love to get this working all the way but I am really new at this and not capable to try my self :(

Anyways this is what I have noticed:
1. The current temperature of the thermostats is not showed anywhere in hass what I can see?
2. The nobø system can be set up with magnetic sensors on windows nearby that deactivates the heat if opened, I'm not sure if this is even possible via the API but it would be great if these were visible in HassIO as well.
3. The thermostats I HassIO shows two different temperatures, one which I think have no feature? I believe it is used on units with both heating and cooling but its confusing on these.
4. In the nobø app it seems to be possible to change to all the different scenes but the "normal". If you set the normal in nobøs app it does not use the mode "program", it goes to "eco".

Which thermostats are you using on your radiators? Im using NCU 1R but will not hesitate to replace them with NCU 2R if necessary for better compatibility. Further Im using latest version HassIO on a raspberry pi (soon to be an intel nuc)

I hope you will continue to develop this and make it a real component, I would love it.

Thanks in advance!
